export const GET_ANIMALS = "GET_ANIMALS";
export const GET_ONE_ANIMAL = "GET_ONE_ANIMAL";
export const ADD_ANIMALS = "ADD_ANIMALS";
export const UPDATE_ANIMALS = "UPDATE_ANIMALS";
export const DELETE_ANIMALS = "DELETE_ANIMALS";